# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Isaac Gaskin
email: gask0032@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Purpose driven blog written by and for the makers at heart, the constantly curious,
  and those who hunger for nuggets of knowledge.  This platform is not intended
  to be a breading ground of tutorials, but rather an attempt to earn partial 
  credit by showing my work.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://igaskin.github.io" # the base hostname & protocol for your site
twitter_username: coder_junk 
github_username:  igaskin 

# Build settings
markdown: kramdown
